[package]
name = "readable_time"
version = "0.1.3"
edition = "2024"
license = "MIT"
description = "Quick and easy date and time lib to get the job done."
repository = "https://github.com/BayonetArch/readable_time"
readme = "README.md"

